Fix shapely TopologyException
Calculating the unary_union of all oceans using the building CRS fails with:
```
shapely.errors.GEOSException: TopologyException: side location conflict
```

To mitigate this issue, we calculate the unary_union using the source
CRS and then transform the shapely polygon afterwards using pyproj.